[package]
name = "curses"
version = "0.1.0"
authors = ["Hans Pistor <hpistor@stetson.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.6.2"}
specs = "0.15.0"
specs-derive = "0.4.0"